name: CI

on:
  push:
    branches:
    - main
    - pipeline-test-parallel
  pull_request:
    branches:
    - main

permissions: { }

jobs:
  golangci:
    name: Lint
    if: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
    - name: Setup Go
      uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # tag=v3.4.0
      with:
        go-version: "1.19"
        check-latest: true
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376 # tag=v3.3.1
      with:
        version: latest

  test:
    if: false
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # tag=v3.4.0
      with:
        go-version: "1.19"
        check-latest: true
    - name: Checkout Repository
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
    - name: Test
      run: make test

  list_tests:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.list_tests.outputs.tests }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: List tests
        id: list_tests
        shell: bash
        run: |
          set -euxo pipefail
          TESTS_JSON=$(grep -r "func Test" *.go --exclude util_test.go | grep -v "_v4" | grep -v "_Latest" | cut -d' ' -f2 | cut -d'(' -f1 | jq -R '.' | jq -c --slurp '[.[]]')
          #echo "tests=$TESTS_JSON" >> $GITHUB_OUTPUT
          echo 'tests=["TestAboutService_Get"]' >> $GITHUB_OUTPUT

  run_tests:
    runs-on: ubuntu-latest
    needs:
      - list_tests
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJSON(needs.list_tests.outputs.tests) }}
        api:
          #- 4.14.4-alpine
          #- 5.0.5
          - 5.1.1
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Start Containers v5
        if: ${{ startsWith(matrix.api, '5.') }}
        shell: bash
        run: |
          docker image pull postgres:18-alpine
          docker image pull ghcr.io/dependencytrack/apiserver:${{ matrix.api }}

          docker run --env 'POSTGRES_DB=dtrack' --env 'POSTGRES_USER=dtrack' --env 'POSTGRES_PASSWORD=dtrack' --publish '5432:5432' --name 'postgres' --health-cmd 'pg_isready -U dtrack -d dtrack' postgres:18-alpine &
          while [ "$(docker inspect -f {{.State.Health.Status}} postgres)" != 'healthy' ]; do sleep 1; done

          docker run --detach \
          --env 'DT_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/dtrack' \
          --env 'DT_DATASOURCE_USERNAME=dtrack' \
          --env 'DT_DATASOURCE_PASSWORD=dtrack' \
          --env 'DT_TELEMETRY_SUBMISSION_ENABLED=false' \
          --publish '8080:8080' \
          --add-host 'host.docker.internal:host-gateway' \
          --volume 'data:/data' \
          --volume '/tmp:/tmp' \
          --name 'api' \
          --read-only \
          --rm \
          ghcr.io/dependencytrack/apiserver:${{ matrix.api }}
          while [ "$(docker inspect -f {{.State.Health.Status}} api)" != 'healthy' ]; do sleep 1; done
      - name: Run v5 tests
        if: ${{ startsWith(matrix.api, '5.') }}
        run: go test -v -cover -run ${{ matrix.test }}
        env:
          DEPENDENCYTRACK_HOST: "https://localhost:8080"
      - name: API Logs
        if: ${{ startsWith(matrix.api, '5.') }}
        run: docker logs api
      - name: DB Logs
        if: ${{ startsWith(matrix.api, '5.') }}
        run: docker logs postgres
