name: CI

on:
  push:
    branches:
    - main
    - pipeline-test-parallel
  pull_request:
    branches:
    - main

permissions: { }

jobs:
  golangci:
    name: Lint
    if: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
    - name: Setup Go
      uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # tag=v3.4.0
      with:
        go-version: "1.19"
        check-latest: true
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376 # tag=v3.3.1
      with:
        version: latest

  test:
    if: false
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # tag=v3.4.0
      with:
        go-version: "1.19"
        check-latest: true
    - name: Checkout Repository
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
    - name: Test
      run: make test

  list_tests:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.list_tests.outputs.tests }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: List tests
        id: list_tests
        shell: bash
        run: |
          set -euxo pipefail
          TESTS_JSON=$(grep -r "func Test" *.go | cut -d' ' -f2 | cut -d'(' -f1 | jq -R '.' | jq -c --slurp '[.[]]')
          echo "tests=$TESTS_JSON" >> $GITHUB_OUTPUT

  run_tests:
    runs-on: ubuntu-latest
    needs:
      - list_tests
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJSON(needs.list_tests.outputs.tests) }}
    steps:
      - run: echo ${{ matrix.test }}
